"""Updated models

Revision ID: 646600f2031a
Revises:
Create Date: 2023-02-08 22:26:04.703880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "646600f2031a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "occupation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_occupation_id"), "occupation", ["id"], unique=True)
    op.create_table(
        "policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("working_hours_amount", sa.Integer(), nullable=True),
        sa.Column("holidays", sa.String(length=300), nullable=True),
        sa.Column("vacation_amount", sa.Integer(), nullable=True),
        sa.Column("sick_leaves_amount", sa.Integer(), nullable=True),
        sa.Column("time_off_amount", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policy_id"), "policy", ["id"], unique=True)
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=True),
        sa.Column("phone_number", sa.String(length=15), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("occupation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["occupation_id"],
            ["occupation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_id"), "employee", ["id"], unique=True)
    op.create_table(
        "shift",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_index(op.f("ix_shift_employee_id"), "shift", ["employee_id"], unique=True)
    op.create_table(
        "timetable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occupation_id", sa.Integer(), nullable=True),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("policy_id", sa.Integer(), nullable=True),
        sa.Column("working_days", sa.String(length=250), nullable=True),
        sa.Column("working_hours", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["occupation_id"],
            ["occupation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shift.employee_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_timetable_id"), "timetable", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timetable_id"), table_name="timetable")
    op.drop_table("timetable")
    op.drop_index(op.f("ix_shift_employee_id"), table_name="shift")
    op.drop_table("shift")
    op.drop_index(op.f("ix_employee_id"), table_name="employee")
    op.drop_table("employee")
    op.drop_index(op.f("ix_policy_id"), table_name="policy")
    op.drop_table("policy")
    op.drop_index(op.f("ix_occupation_id"), table_name="occupation")
    op.drop_table("occupation")
    # ### end Alembic commands ###
