"""Updated models

Revision ID: 8e03b213edc1
Revises: 646600f2031a
Create Date: 2023-02-09 00:19:57.962044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e03b213edc1'
down_revision = '646600f2031a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'occupation', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'occupation', type_='unique')
    # ### end Alembic commands ###
