name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true
    - name: Install pylint
      run: |
        poetry add pylint
    - name: Analysing the code with pylint
      run: |
        python -m poetry run pylint $(git ls-files '*.py')
